### PR TITLE
Enforce yarn >=0.27.5

### PR DESCRIPTION
**Pull request by AdamLiechty**

### CODE REVIEW

**Comment by nickatdivvy** [comment]
I've never used brew to install yarn (and that's OSX/(linux?) specific). npm install -g yarn works as well

**Comment by theckman** [comment]
@nickatdivvy to quote the NPM installation page:
>Note: Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.
>
>For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

* https://yarnpkg.com/lang/en/docs/install/#alternatives-tab

**Comment by AdamLiechty** [comment]
Updated text to instruct you to view the website for other OSes

**Comment by nbclark** [comment]
Good to know

**Pull request merged**
